# Generated by Django 5.1.1 on 2024-09-27 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist5', '0002_alter_todoitem_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='reminder_time_delta',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='reminder_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
